source 'https://rubygems.org'

# This is a stock Rails 4.2 Gemfile...

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'compass-rails'

# ... with the exception of this line, which lets us run the application locally.
gem 'chef-web-core', path: '../../../'

group :development, :test do
  gem 'byebug'
  gem 'spring'
end
